#! /bin/bash

bspc config border_width        2
bspc config window_gap         06

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true
bspc config focus_follows_pointer true

. $HOME/.Xresourceshelper
bspc config focused_border_color "$(colour_from_xresources "col_focussed")"
bspc config active_border_color "$(colour_from_xresources "col_active")"
bspc config normal_border_color "$(colour_from_xresources "col_fg")"
bspc rule -a zoom state=floating center=on follow=on border=off

bspc config presel_feedback_color '#FFFFFF'
bspc monitor -d I II III IV V VI VII VIII IX X

# make sure we source our local configuration if one exists
if [[ -e "$HOME/.config/bspwm/bspwmrc.local" ]];
then
	. $HOME/.config/bspwm/bspwmrc.local
fi

polybars.sh
nm-applet &
